### ISSUE TITLE
[Error] Compile errors

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/mod-instance-reset#1]
After recent major updates, module is not ready for compile.

**Comment by BarbzYHOOL** [comment]
lol put errors plz

**Comment by Nefertumm** [comment]
Just change the gossip to the newer version and that's it

**Comment by BarbzYHOOL** [comment]
i wouldn't know how to do it from reading that comment tho xD

**Comment by Knindzagxg** [comment]
Not putting whole info Barbz, it's error like all previous modules had due new version.
It's just that we haven't updated older and putting message so someone can check.

**Comment by BarbzYHOOL** [comment]
ok if someone understands what must be done :rofl:

**Comment by Nefertumm** [comment]
Done, test when you can :)

**Comment by Helias** [comment]
Recently compiled, no errors
