### ISSUE TITLE
can not disable this module

### ISSUE THREAD

**Issue by carloskaine** [azerothcore/mod-instance-reset#23]
can not disable this module when set the instanceReset.Enable=false

**Comment by pangolp** [comment]
Greetings, I did some tests, and it could be deactivated, but now, what is going to happen is that it will not show the gossip, but the text, in case the module is deactivated. Among other changes that I made, and perhaps we will continue adding more suggestions, than those reported. I thank you for the report. Greetings.

`instanceReset.Enable = false`

![WoWScrnShot_031424_230956](https://github.com/azerothcore/mod-instance-reset/assets/2810187/acc8806a-fbd0-436a-9e8c-f7096e129ce4)

`instanceReset.Enable = true`

![WoWScrnShot_031424_231122](https://github.com/azerothcore/mod-instance-reset/assets/2810187/61001e39-8cc4-48cb-990f-397d082ad0b8)
![WoWScrnShot_031424_231132](https://github.com/azerothcore/mod-instance-reset/assets/2810187/810c5c5d-79bb-476f-b3a3-7d071b161455)
