### ISSUE TITLE
Need to improve README

### ISSUE THREAD

**Issue by slayoffer** [azerothcore/mod-instance-reset#24]
Hello.

Please add guide of how to summon instance reset NPC in the readme.

I have no idea of how to use this module xD

**Comment by slayoffer** [comment]
Figured it out myself.

Need to type: `.npc add 300000`

Will make pull request to README later

**Comment by pangolp** [comment]
Greetings, I'm about to upload a pull request, and I'm going to approve it to change what you mention. Thank you.
