### ISSUE TITLE
Bug: Outdated SQL file

### ISSUE THREAD

**Issue by ggvvaa** [azerothcore/mod-instance-reset#29]
### Current Behaviour

The npc add 300000 dose not spawn in the npc.

### Expected Behaviour

The npc add 300000 should spawn in the npc.

### Steps to reproduce the problem

1. Step: Follow the described installation steps.
2. Step: run the .npc add 300000 command as admin

### Extra Notes

From what I have gathered the problem seems to originate from the SQL file 'mod_instance_reset_2024_03_14.sql'. I tried sourcing the sql file manually and I got an error saying the "modelid1" field dosen't exists. I used HeidieSQL to check the "creature_template" table manually and indeed there was no entry 300000 in the table.

### AC rev. hash/commit

[29131dc](https://github.com/azerothcore/mod-instance-reset/commit/29131dc2b33324c248f8f542fe359cb90cce4928)

### Operating system

Debian 12 x64

**Comment by acore-crap** [comment]
#28

**Comment by Helias** [comment]
I merged the PR, the issue should be closed by https://github.com/azerothcore/mod-instance-reset/pull/28
thanks!

**Comment by ggvvaa** [comment]
Thank you for your response. I updated the mod, and can now spawn the npc.
